name: Build

on:
  push:
    branches: [dev, stage, prod]
  pull_request:
    branches: [dev, stage, prod]
    paths:
      - 'apps/**'
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r apps/retail_api/requirements.txt

      - name: Build Docker image
        run: docker build -t apps/retail_pi:latest apps/retail_api

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft apps/retail_api -o json > sbom.json

      - name: Install Cosign
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

#      - name: Sign Docker image
#        env:
#          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
#        run: cosign sign --key env://COSIGN_KEY apps/retail_api:latest

#      - name: Publish build metadata
#        run: |
#          echo "Git SHA: ${{ github.sha }}"
#          echo "SBOM hash: $(sha256sum sbom.json)"
#          cosign verify apps/retail_api:latest > cosign_bundle.txt
#          echo "Cosign bundle: $(cat cosign_bundle.txt)"

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}

#      - name: Log in to Amazon ECR
#        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

#      - name: Tag and Push Docker image to ECR
#        run: |
#          docker tag apps/retail_api:latest ${{ secrets.ECR_REGISTRY }}/apps/retail_api:latest
#          docker push ${{ secrets.ECR_REGISTRY }}/apps/retail_api:latest

