# Example: .github/workflows/build.yml
name: Build

on:
  pull_request:
    branches: [dev, stage, prod]
    paths:
      - 'apps/**'
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build step
        run: echo "Building app..."

