name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback (dev/stage/prod)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
          aws-region: ap-south-1

      - name: Fetch last known good version from SSM
        id: fetch_version
        run: |
          VERSION=$(aws ssm get-parameter --name "/retail-api/last-good-version" --query "Parameter.Value" --output text)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rollback with Terragrunt
        run: |
          terragrunt apply \
            --terragrunt-working-dir infra/terragrunt/retail-${{ github.event.inputs.environment }} \
            --var="version=${{ steps.fetch_version.outputs.version }}" \
            --auto-approve

