name: Test

on:
  push:
    branches:
      - dev
      - stage
      - prod

`:wq  pull_request:
    branches:
      - dev
      - stage
      - prod
    paths:
      - 'apps/**'
      - 'infra/**'

  workflow_run:
    workflows:
      - Build
    types:
      - completed



jobs:
  test:
    runs-on: ubuntu-latest

#    services:
#      localstack:
#        image: localstack/localstack:latest
#        ports:
#          - 4566:4566
#        env:
#          SERVICES: s3,dynamodb
#          DEBUG: 1
#        options: >-
#          --health-cmd "curl -f http://localhost:4566/health || exit 1"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r apps/retail-api/requirements.txt

      - name: Install test tools
        run: pip install pytest-cov

      - name: Run unit tests with coverage
        run: pytest --cov=apps/retail-api --cov-fail-under=90

      - name: Run contract tests with Pact
        run: pact-verifier verify --provider-base-url=http://localhost:8000

      - name: Run integration tests with Docker Compose
        run: docker-compose -f tests/docker-compose.yml up --abort-on-container-exit

